--PRODUCTS
INSERT INTO PRODUCT (NAME, PRICE, QUANTITY_AVAILABLE, SHOP_CODE) VALUES ('Piccolo', '59.99', '6', 'PI90800');
INSERT INTO PRODUCT (NAME, PRICE, QUANTITY_AVAILABLE, SHOP_CODE) VALUES ('Lily', '99.99', '6', 'PI90870');
INSERT INTO PRODUCT (NAME, PRICE, QUANTITY_AVAILABLE, SHOP_CODE) VALUES ('Carma chains', '9.99', '20', 'PI90899');
