--USERS
INSERT INTO USER (USERNAME, PASSWORD, ENABLED) VALUES('user', 'password', TRUE);
INSERT INTO USER (USERNAME, PASSWORD, ENABLED) VALUES('admin', 'password', TRUE);
INSERT INTO USER (USERNAME, PASSWORD, ENABLED) VALUES('test@mail.com', '12345', TRUE);
INSERT INTO USER (USERNAME, PASSWORD, ENABLED) VALUES('new@mail.com', '12345', TRUE);

--AUTHORITIES
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES('user', 'ROLE_USER');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES('admin', 'ROLE_ADMIN');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES('test@mail.com', 'ROLE_USER');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES('new@mail.com', 'ROLE_USER');